# Generated by Django 4.2 on 2023-05-05 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ImageUploadapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
